# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            KrashDev.com
subtitle:         Nathan Karasch's Portfolio
description:      This is the portfolio site for Nathan Karasch, Software Engineer.
keywords:         software development portfolio engineering projects blog resume
language:         "en"

baseurl:          "/" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:        /blog/:categories/:title
cover:            /assets/mountain-cover.jpg
disqus_shortname: "krashdev"

# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor, "developer-tools"]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  blanklines: true
  startings: [head, body]